### ISSUE TITLE
Crashes on dropbox sync

### ISSUE THREAD

**Issue by niknah** [martinstoeckli/SilentNotes#16]
Hi,

Nice app.  When I try to use GMX sync it says that I've got the wrong password but I can login normally with the GMX website. I can't seem to get dropbox working, it crashes here...

2019-06-18 07:53:14.246 14252-14252/? I/MonoDroid: UNHANDLED EXCEPTION:
2019-06-18 07:53:14.275 14252-14252/? I/MonoDroid: System.InvalidOperationException: Type not found in cache: SilentNotes.Services.IStoryBoardService.
2019-06-18 07:53:14.275 14252-14252/? I/MonoDroid:   at GalaSoft.MvvmLight.Ioc.SimpleIoc.DoGetService (System.Type serviceType, System.String key, System.Boolean cache) [0x0005d] in <4bfe803b47234f56b6c30e8bc3e0a4b9>:0 
2019-06-18 07:53:14.275 14252-14252/? I/MonoDroid:   at GalaSoft.MvvmLight.Ioc.SimpleIoc.GetInstance[TService] () [0x00000] in <4bfe803b47234f56b6c30e8bc3e0a4b9>:0 
2019-06-18 07:53:14.275 14252-14252/? I/MonoDroid:   at SilentNotes.Ioc.GetOrCreate[T] () [0x00005] in <e99ad0a7ca684a81abb6acc698bf2a6b>:0 
2019-06-18 07:53:14.275 14252-14252/? I/MonoDroid:   at SilentNotes.Android.CloudStorageRedirectActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0001d] in <3622252809f7410abda47474a4c2c7c1>:0 
2019-06-18 07:53:14.275 14252-14252/? I/MonoDroid:   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <b0a82ae599024c39a5912192e91edd0f>:0 
2019-06-18 07:53:14.275 14252-14252/? I/MonoDroid:     at (wrapper dynamic-method) System.Object.3(intptr,intptr,intptr)
2019-06-18 07:53:14.287 14252-14252/? W/art: JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
2019-06-18 07:53:14.295 14252-14252/? D/AndroidRuntime: Shutting down VM
2019-06-18 07:53:14.305 14252-14252/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ch.martinstoeckli.silentnotes, PID: 14252
    android.runtime.JavaProxyThrowable: System.InvalidOperationException: Type not found in cache: SilentNotes.Services.IStoryBoardService.
      at GalaSoft.MvvmLight.Ioc.SimpleIoc.DoGetService (System.Type serviceType, System.String key, System.Boolean cache) [0x0005d] in <4bfe803b47234f56b6c30e8bc3e0a4b9>:0 
      at GalaSoft.MvvmLight.Ioc.SimpleIoc.GetInstance[TService] () [0x00000] in <4bfe803b47234f56b6c30e8bc3e0a4b9>:0 
      at SilentNotes.Ioc.GetOrCreate[T] () [0x00005] in <e99ad0a7ca684a81abb6acc698bf2a6b>:0 
      at SilentNotes.Android.CloudStorageRedirectActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0001d] in <3622252809f7410abda47474a4c2c7c1>:0 
      at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <b0a82ae599024c39a5912192e91edd0f>:0 
        at (wrapper dynamic-method) System.Object.3(intptr,intptr,intptr)
        at md57b762c29a856a08758177b308884e445.CloudStorageRedirectActivity.n_onCreate(Native Method)
        at md57b762c29a856a08758177b308884e445.CloudStorageRedirectActivity.onCreate(CloudStorageRedirectActivity.java:29)
        at android.app.Activity.performCreate(Activity.java:6684)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
2019-06-18 07:53:14.313 1166-5556/? W/ActivityManager:   Force finishing activity ch.martinstoeckli.silentnotes/md57b762c29a856a08758177b308884e445.CloudStorageRedirectActivity

**Comment by martinstoeckli** [comment]
Thanks for your error description.
I just double checked both logins, but couldn't reproduce the problems. So maybe you could help me answering some questions?

1. Did the problem occur on the Windows or the Android platform?
2. GMX Login: Is there anything special about your password, maybe some special unicode characters like Emojis? Did you type it in, or copied it from somewhere (password manager)? Can you double check for whitespaces at the begin or end of the password?
3. Dropbox login: At the moment when the Dropbox website redirected to the app (after allowing access), was SilentNotes still running (should be), or was it somehow closed and had to restart? This is mainly important if it where running on Windows.

**Comment by niknah** [comment]
Hi Martin,

I was using the Android app from the Play store.

Nothing funny with my GMX login.  But on the app it asks for a username.
On the GMX web site it asks for an email.

I got into the dropbox website.  When I pressed the button to allow, it
went back to the app and it crashed.

**Comment by martinstoeckli** [comment]
Hi Niknah

Thanks for the detailed information, I just tried both logins with the Android emulator and could reproduce the Dropbox exeption. I will dig into this and let you know as soon as I know more. For the GMX login, could you try with the email adress please, the username for GMX is in fact the email adress, maybe I should improve the user dialog there and make this clear.

**Comment by niknah** [comment]
I am using GMX.com
I just noticed that I can't login to gmx.net with that account.  Maybe
they're different?

**Comment by martinstoeckli** [comment]
Oh indeed `gmx.net` is not the same as `gmx.com`, I cannot login to gmx.com with my own GMX email address! Thanks for checking this out.

Actually SilentNotes connects to GMX via WebDav to https://webdav.mc.gmx.net/ so it seems logical that you cannot login there. Though if we knew the WebDav address for gmx.com you could choose WebDav (instead of GMX) as the online storage type and connect to this path, a guick research revealed that https://storage-file-eu.gmx.com/ might be this address.

Currently I do a rework of the online-storage access, to support other types like Google drive. I will include a fix for DropBox, though this could take some time. I think I already found the culprit, the redirect from the browser sometimes starts a new instance of SilentNotes in a separate process.

**Comment by martinstoeckli** [comment]
Issue is solved in Version 2.5.2

**Comment by martinstoeckli** [comment]
@niknah I would like to add support for gmx.com e-mail addresses for the next release. If you could do a quick test with a WebDav online storage (instead of GMX) and try the url https://storage-file-eu.gmx.com/ this would help me very much. Thanks: Martin

**Comment by niknah** [comment]
Thanks the webdav url works.  

If I had uninstalled the app, is there a way to get the transfer code back when I install it again?

**Comment by martinstoeckli** [comment]
Thanks a lot for the confirmation, currently I'm waiting on the response from the GMX support. If SilentNotes is installed on another device, you can get the transfer code from there, otherwise there is no way beacuse Android will clean up all data when uninstalling an app.

**Comment by martinstoeckli** [comment]
@niknah - Since version 3.0.0 SilentNotes now also supports gmx.com addresses.
